package sakethh.tenmin.mail.ui.settings

enum class Setting {
    USE_DARK_THEME, USE_DIM_DARK_THEME, USE_DYNAMIC_THEMING, AUTO_REFRESH_MAILS, USE_IN_APP_BROWSER, AUTO_CHECK_FOR_UPDATES, SHOW_DESCRIPTION_FOR_SETTINGS
}