package sakethh.tenmin.mail

enum class NavigationRoutes {
    INBOX, ABOUT, STARTUP, SIGN_IN, HOME, ACCOUNTS, SETTINGS, SPECIFIC_SETTINGS,
    ALL_INBOXES, STARRED, ARCHIVE, TRASH, ALL_STARRED, ALL_ARCHIVE, ALL_TRASH
}